# .config/hypr/monitors.conf
# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# Gian's edits
# MicroPC 2
monitor=DSI-1,preferred,auto,auto,transform,3
# Samsung C43J89x UltraWide
monitor=DP-2,3840x1200@120.00Hz,auto,auto
# viture (primary when connected)
monitor=DP-1,preferred,auto,1.25
# ---

# .config/hypr/input.conf
# https://learn.omacom.io/2/the-omarchy-manual/78/keyboard-mouse-trackpad#use-alt-as-super
input {
  kb_options = compose:caps,altwin:swap_alt_win
}
# ---

# .config/hypr/looknfeel.conf
# Change the default Omarchy look'n'feel
general {
    # Change to niri-like side-scrolling layout
    layout = scrolling
}
# https://wiki.hyprland.org/Configuring/Layouts/Scrolling/
scrolling {
    column_width = 0.80 # 2/3 of the screen width
}
# ---

# .config/hypr/autostart.conf
# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- ~/.config/hypr/scripts/auto-rotate.sh
exec-once = uwsm-app -- ~/.config/hypr/scripts/monitor-recover-watch.sh
exec-once = uwsm-app -- ~/.config/hypr/scripts/workspace-follow-external.sh
# ---

# .config/hypr/bindings.conf
# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Override app bindings
unbind = SUPER SHIFT, SLASH
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- bitwarden
unbind = SUPER SHIFT, A
bindd = SUPER SHIFT, A, Claude, exec, omarchy-launch-webapp "https://claude.ai"

# Override default laptop display toggles with user-owned scripts
unbind = SUPER CTRL, Delete
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, ~/.config/hypr/scripts/monitor-internal-toggle.sh toggle
unbind = SUPER CTRL ALT, Delete
bindd = SUPER CTRL ALT, Delete, Toggle laptop display mirroring, exec, ~/.config/hypr/scripts/monitor-internal-mirror-toggle.sh toggle
#---

# https://github.com/Zeus-Deus/hyprmode
# HyprMode - Float and center (for Alacritty/Kitty)
unbind = SUPER SHIFT, P
bindd = SUPER SHIFT, P, Display switcher, exec, alacritty --class hyprmode -e hyprmode
windowrule = float on, center on, size 597 530, opacity 0.95, match:class ^(hyprmode)$
# ---
